//============================================================================
// Name        : PalindromeString.cpp
// Author      : dmtwong
// Version     :
// Copyright   : 
// Description : Hello World in C++, Ansi-style
//============================================================================

#include <iostream>
#include <string>
#include <cmath>
#include <algorithm>
using namespace std;

//int Solution::isPalindrome(string A) {
int isPalindrome(string A) {
	int len_A = A.length();
	string full_char = "abcdefghijklmnopqrstuvwxyz0123456789";
	transform(A.begin(), A.end(), A.begin(),
	    [](unsigned char sing_char){ return std::tolower(sing_char); });
//	cout << A << endl;
	string trim_result = "";

	for (int i = 0; i < len_A; i++){
		if(int(full_char.find(A[i])) != -1){
			trim_result += A[i];
		}
	}
	int isPal = 1;
	int i = 0;
	int len_trim = trim_result.size();
	int j = len_trim - 1;
	int counter = int(len_trim/2);
//	cout << trim_result << endl;

//	while((i + abs(j) < len_trim) and isPal){
	while(counter > 0 and isPal){
//		cout << trim_result[i] << endl;
//		cout << trim_result[j] << endl;
		if(trim_result[i] == trim_result[j]){
//			cout << counter << endl;
			i += 1;
			j -= 1;
			counter -= 1;
		} else {
//			cout << counter << endl;
			isPal = 0;
		}
	}
	return int(isPal);
}


int main() {
	string input_1 = "A man, a plan, a canal: Panama";
	string input_2 = "race a car";
	string input_3 = "1a2";
	string input_4 = "'";
	string input_5 = "aAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaaaAaAaAAaa";

	int test_1 = isPalindrome(input_1);
	int test_2 = isPalindrome(input_2);
	int test_3 = isPalindrome(input_3);
	int test_4 = isPalindrome(input_4);
	int test_5 = isPalindrome(input_5);
	cout << test_1 << endl; // prints
	cout << test_2 << endl;
	cout << test_3 << endl;
	cout << test_4 << endl;
	cout << test_5 << endl;
	return 0;
}

/* Editorial
int Solution::isPalindrome(string A) {
    int i = 0, j = (int)A.size() - 1;
    while(i < j)
    {
        while(i < j && !isalnum(A[i])) i++;
        while(i < j && !isalnum(A[j])) j--;
        if (toupper(A[i]) != toupper(A[j])) return false;
        i++;
        j--;
    }
    return true;
}
 *
 */
